// Wuxing (五行) analysis engine
// Five Elements interaction: generating (生) and overcoming (克) cycles

const ELEMENT_GEN: Record<string, string> = {
  木: "水", // Wood is generated by Water
  火: "木", // Fire is generated by Wood
  土: "火", // Earth is generated by Fire
  金: "土", // Metal is generated by Earth
  水: "金", // Water is generated by Metal
};

const ELEMENT_SHENG: Record<string, string> = {
  木: "火", // Wood generates Fire
  火: "土", // Fire generates Earth
  土: "金", // Earth generates Metal
  金: "水", // Metal generates Water
  水: "木", // Water generates Wood
};

const ELEMENT_KE: Record<string, string> = {
  木: "土", // Wood overcomes Earth
  土: "水", // Earth overcomes Water
  水: "火", // Water overcomes Fire
  火: "金", // Fire overcomes Metal
  金: "木", // Metal overcomes Wood
};

const ELEMENT_BEATEN_BY: Record<string, string> = {
  木: "金", // Wood is overcome by Metal
  火: "水", // Fire is overcome by Water
  土: "木", // Earth is overcome by Wood
  金: "火", // Metal is overcome by Fire
  水: "土", // Water is overcome by Earth
};

const ELEMENT_ORDER = ["金", "木", "水", "火", "土"];
const ELEMENT_EN: Record<string, string> = {
  木: "Wood", 火: "Fire", 土: "Earth", 金: "Metal", 水: "Water",
};

export interface WuxingAnalysis {
  dayMaster: string;         // 日主 element
  counts: Record<string, number>;
  strongest: string;
  weakest: string;
  favorable: string[];       // 喜用神
  unfavorable: string[];     // 忌神
  balanced: boolean;
  descriptionEn: string;
}

export function analyzeWuxing(
  dayStemElement: string,
  elementCounts: Record<string, number>
): WuxingAnalysis {
  const sorted = Object.entries(elementCounts).sort((a, b) => b[1] - a[1]);
  const strongest = sorted[0][0];
  const weakest = sorted[4][0];
  const dayMaster = dayStemElement;

  // Calculate favorable elements
  const favorable: string[] = [];
  const unfavorable: string[] = [];

  const dayCount = elementCounts[dayMaster] || 0;
  const maxCount = sorted[0][1];
  const minCount = sorted[4][1];

  // If day master is too weak, add elements that generate it
  if (dayCount <= 2 && maxCount >= 4) {
    const generator = ELEMENT_GEN[dayMaster];
    if (generator && !favorable.includes(generator)) favorable.push(generator);
    if (!favorable.includes(dayMaster)) favorable.push(dayMaster);

    const overcomer = ELEMENT_BEATEN_BY[dayMaster];
    if (overcomer && !unfavorable.includes(overcomer)) unfavorable.push(overcomer);
  }

  // If day master is very strong, drain it
  if (dayCount >= 4) {
    const drained = ELEMENT_SHENG[dayMaster];
    if (drained && !favorable.includes(drained)) favorable.push(drained);
    const overcome = ELEMENT_KE[dayMaster];
    if (overcome && !favorable.includes(overcome)) favorable.push(overcome);
    if (!unfavorable.includes(dayMaster)) unfavorable.push(dayMaster);
  }

  // Fallback: always include day master generator
  if (favorable.length === 0) {
    const gen = ELEMENT_GEN[dayMaster];
    if (gen) favorable.push(gen);
    favorable.push(dayMaster);
  }

  // Build English description — warm, conversational
  const dayEl = ELEMENT_EN[dayMaster] || dayMaster;
  const descParts: string[] = [];

  // Day master with personality language
  const dayPersonalities: Record<string, string> = {
    "木": "You're like a towering tree — you grow steadily, think independently, and lead with quiet strength.",
    "火": "You burn bright — passionate, charismatic, and naturally drawn to the spotlight.",
    "土": "You're the steady ground beneath others' feet — reliable, nurturing, and deeply grounded.",
    "金": "You carry a sharp clarity — disciplined, principled, with an eye for what truly matters.",
    "水": "You flow like deep water — intuitive, wise, and endlessly adaptable to whatever life brings.",
  };
  descParts.push(dayPersonalities[dayMaster] || `Your Day Master is ${dayEl} (${dayMaster}).`);

  if (maxCount - minCount <= 2) {
    descParts.push("Your Five Elements sit in rare balance — a naturally harmonious foundation that serves you well in any path you choose.");
  } else {
    const strongEl = ELEMENT_EN[strongest] || strongest;
    const weakEl = ELEMENT_EN[weakest] || weakest;
    const favList = favorable.map(e => ELEMENT_EN[e] || e).join(" and ");
    descParts.push(`Your chart leans strongly toward ${strongEl} while ${weakEl} runs a bit thin. What brings you back into balance: more ${favList}.`);
  }

  return {
    dayMaster,
    counts: elementCounts,
    strongest,
    weakest,
    favorable,
    unfavorable,
    balanced: maxCount - minCount <= 2,
    descriptionEn: descParts.join(" "),
  };
}

export function getFavorableElements(bazi: {
  day: { wuxing: string };
  elements: Record<string, number>;
}): string[] {
  const analysis = analyzeWuxing(bazi.day.wuxing, bazi.elements);
  return analysis.favorable;
}

export { ELEMENT_GEN, ELEMENT_SHENG, ELEMENT_KE, ELEMENT_BEATEN_BY, ELEMENT_ORDER, ELEMENT_EN };
