// GET /api/daily-social — today's hexagram + ready-to-post copy for the whole
// social matrix (X/Twitter, Telegram, Reddit, Pinterest) in 4 languages.
// Content is generated by src/lib/social/content.ts (single source of truth).

import { getDailySocialPosts } from "@/lib/social/content";

export const runtime = "nodejs";

export async function GET() {
  const social = getDailySocialPosts();

  return Response.json(social, {
    headers: { "Cache-Control": "public, max-age=3600, s-maxage=3600" },
  });
}

