import type { Metadata } from "next";
import { Link } from "@/navigation";
import { MATCHES, GROUPS, type WCMatch, getMatchesByDate } from "@/data/world-cup-2026";
import { predictMatch, getStageName, type MatchPrediction } from "@/lib/world-cup";
import { BASE_URL } from "@/lib/config";

type Props = { params: { locale: string } };

const UI: Record<string, {
  title: string; desc: string; ogTitle: string; ogDesc: string;
  hero: string; subtitle: string; intro: string;
  todayLabel: string; upcomingLabel: string; fullScheduleLabel: string;
  noMatches: string; groupLabel: string; vs: string;
  cta: string; ctaText: string; disclaimer: string; groupsLabel: string;
  warningBanner: string; warningDetail: string;
}> = {
  en: {
    title: "I Ching World Cup 2026 Predictions — For Fun Oracle Match Forecast | Chinese Culture Studio",
    desc: "For entertainment only. Ancient I Ching hexagram predictions for 2026 FIFA World Cup matches. NOT betting advice — deterministic oracle fun based on match metadata.",
    ogTitle: "I Ching World Cup 2026 Predictions", ogDesc: "For fun only: Ancient Chinese oracle meets modern football. Not betting advice.",
    hero: "I Ching x World Cup 2026", subtitle: "The 3,000-year-old Book of Changes meets the world's biggest tournament. Every match, one hexagram.",
    intro: "Below are I Ching hexagram-based predictions for every match of the 2026 FIFA World Cup (June 11 - July 19). Each prediction is deterministically generated from the match date and teams — the same match always yields the same hexagram.",
    todayLabel: "Today's Predictions", upcomingLabel: "Upcoming Matches", fullScheduleLabel: "Full Schedule",
    noMatches: "No matches scheduled for this date.", groupLabel: "Group", vs: "vs",
    cta: "Try I Ching Divination", ctaText: "Ask the I Ching your own question — about football or anything else.",
    disclaimer: "Disclaimer: This page is for entertainment purposes only. The I Ching (Book of Changes) is a 3,000-year-old Chinese philosophical and wisdom tradition, not a predictive tool. All hexagram predictions on this page are deterministically generated by a mathematical hash of match metadata (date + team names) and have no relationship to actual match outcomes. Do NOT use this content for gambling, betting, or any financial decisions. Chinese Culture Studio accepts no liability for any losses incurred through reliance on this entertainment content.",
    warningBanner: "FOR ENTERTAINMENT ONLY — NOT BETTING ADVICE",
    warningDetail: "These predictions are algorithmically generated from match metadata. They have zero predictive accuracy and are purely for fun. Do not use for gambling or betting decisions.",
    groupsLabel: "Groups",
  },
  ru: {
    title: "И-Цзин ЧМ-2026 — Развлекательные Прогнозы | Chinese Culture Studio",
    desc: "Только для развлечения. Древние гексаграммы И-Цзин для матчей ЧМ-2026. НЕ советы для ставок — детерминированное развлечение на основе метаданных матча.",
    ogTitle: "И-Цзин Прогнозы на ЧМ-2026", ogDesc: "Только для развлечения: древний оракул встречает футбол. Не советы для ставок.",
    hero: "И-Цзин x ЧМ-2026", subtitle: "3000-летняя Книга Перемен встречает крупнейший турнир мира.",
    intro: "Прогнозы на основе гексаграмм И-Цзин для каждого матча ЧМ-2026 (11 июня - 19 июля). Каждое предсказание детерминировано генерируется из даты и команд.",
    todayLabel: "Прогнозы на Сегодня", upcomingLabel: "Предстоящие Матчи", fullScheduleLabel: "Полное Расписание",
    noMatches: "На эту дату матчей нет.", groupLabel: "Группа", vs: "vs",
    cta: "Гадание И-Цзин", ctaText: "Задайте И-Цзин свой вопрос.",
    disclaimer: "Отказ от ответственности: эта страница предназначена исключительно для развлечения. И-Цзин (Книга Перемен) — это 3000-летняя китайская философская традиция мудрости, а не инструмент прогнозирования. Все предсказания генерируются математическим хешем метаданных матча (дата + названия команд) и не имеют никакого отношения к реальным результатам. НЕ используйте этот контент для ставок, азартных игр или финансовых решений. Chinese Culture Studio не несёт ответственности за любые убытки.",
    warningBanner: "ТОЛЬКО ДЛЯ РАЗВЛЕЧЕНИЯ — НЕ СОВЕТЫ ДЛЯ СТАВОК",
    warningDetail: "Эти прогнозы генерируются алгоритмически. Они не имеют предсказательной точности и предназначены исключительно для развлечения. Не используйте для азартных игр или ставок.",
    groupsLabel: "Группы",
  },
  ja: {
    title: "易経 2026年W杯 勝敗予想 — 娯楽目的 | Chinese Culture Studio",
    desc: "娯楽目的のみ。古代易経による2026年FIFAワールドカップ試合の卦。賭博アドバイスではありません — 試合メタデータに基づく娯楽です。",
    ogTitle: "易経 2026年W杯 勝敗予想", ogDesc: "娯楽目的のみ：古代中国のオラクルが現代サッカーと出会う。賭博アドバイスではありません。",
    hero: "易経 x 2026 W杯", subtitle: "3000年の歴史を持つ易経が世界最大のトーナメントと出会う。",
    intro: "2026年FIFAワールドカップ（6月11日〜7月19日）の全試合に対する易経八卦予測です。各予測は試合日とチーム名から決定論的に生成されます。",
    todayLabel: "本日の予想", upcomingLabel: "今後の試合", fullScheduleLabel: "全スケジュール",
    noMatches: "この日に試合はありません。", groupLabel: "グループ", vs: "vs",
    cta: "易経占い", ctaText: "易経に質問してみてください。",
    disclaimer: "免責事項：このページは娯楽目的のみで提供されています。易経（易）は3000年の歴史を持つ中国の哲学的・智慧的伝統であり、予測ツールではありません。このページのすべての卦予測は、試合のメタデータ（日付＋チーム名）の数学的ハッシュによって決定論的に生成されており、実際の試合結果とは一切関係がありません。ギャンブル、賭博、または金銭的判断にこのコンテンツを使用しないでください。Chinese Culture Studioは、この娯楽コンテンツへの依拠によって生じたいかなる損失についても責任を負いません。",
    warningBanner: "娯楽目的のみ — 賭博アドバイスではありません",
    warningDetail: "これらの予測はアルゴリズムで生成されています。予測精度はゼロであり、純粋に娯楽のためのものです。ギャンブルや賭博に使用しないでください。",
    groupsLabel: "グループ",
  },
  ko: {
    title: "주역 2026 월드컵 예측 — 오락 목적 | Chinese Culture Studio",
    desc: "오락 목적으로만 제공. 고대 주역을 통한 2026 FIFA 월드컵 경기 괘. 도박 조언이 아닙니다 — 경기 메타데이터 기반 결정론적 오락.",
    ogTitle: "주역 2026 월드컵 예측", ogDesc: "오락 목적: 고대 중국의 오라클이 현대 축구를 만나다. 도박 조언이 아닙니다.",
    hero: "주역 x 2026 월드컵", subtitle: "3,000년 된 역경이 세계 최대의 토너먼트를 만납니다.",
    intro: "2026 FIFA 월드컵(6월 11일~7월 19일)의 모든 경기에 대한 주역 괘 예측입니다. 각 예측은 경기 날짜와 팀 이름에서 결정론적으로 생성됩니다.",
    todayLabel: "오늘의 예측", upcomingLabel: "예정된 경기", fullScheduleLabel: "전체 일정",
    noMatches: "경기가 없습니다.", groupLabel: "그룹", vs: "vs",
    cta: "주역 점술", ctaText: "주역에게 질문해보세요.",
    disclaimer: "면책 조항: 이 페이지는 오락 목적으로만 제공됩니다. 주역(역경)은 3,000년 된 중국의 철학적·지혜적 전통이며 예측 도구가 아닙니다. 이 페이지의 모든 괘 예측은 경기 메타데이터(날짜 + 팀 이름)의 수학적 해시에 의해 결정론적으로 생성되며 실제 경기 결과와 아무런 관련이 없습니다. 도박, 베팅 또는 금전적 결정에 이 콘텐츠를 사용하지 마십시오. Chinese Culture Studio는 이 오락 콘텐츠에 의존하여 발생한 손실에 대해 어떠한 책임도 지지 않습니다.",
    warningBanner: "오락 목적으로만 제공 — 도박 조언이 아님",
    warningDetail: "이 예측은 알고리즘으로 생성됩니다. 예측 정확도는 0이며 순수한 오락용입니다. 도박이나 베팅에 사용하지 마십시오.",
    groupsLabel: "조",
  },
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const u = UI[params.locale] || UI.en;
  return {
    title: u.title, description: u.desc,
    openGraph: { title: u.ogTitle, description: u.ogDesc },
    robots: "index, follow",
    alternates: {
      languages: {
        en: `${BASE_URL}/world-cup`,
        ru: `${BASE_URL}/ru/world-cup`,
        ja: `${BASE_URL}/ja/world-cup`,
        ko: `${BASE_URL}/ko/world-cup`,
      },
    },
  };
}

function PredictionCard({ p, locale }: { p: MatchPrediction; locale: string }) {
  return (
    <div className="card-classic p-4">
      <div className="flex items-center justify-between mb-2">
        <div className="text-sm font-semibold text-stone-700">
          {p.match.home} <span className="text-stone-400 text-xs">vs</span> {p.match.away}
        </div>
        <span className="text-xs text-stone-400">{getStageName(p.match.stage, locale)}</span>
      </div>
      <div className="flex items-center gap-3 mb-2">
        <div className="w-9 h-9 rounded-full flex items-center justify-center text-sm font-bold text-white" style={{ backgroundColor: "var(--accent)" }}>
          {p.hexagram.id}
        </div>
        <div>
          <div className="text-sm font-medium" style={{ color: "var(--accent)" }}>{p.hexagram.nameEn}</div>
          <div className="text-xs text-stone-400">{p.hexagram.nameZh} - {p.hexagram.pinyin}</div>
        </div>
      </div>
      <p className="text-xs text-stone-500 italic mb-1">&ldquo;{p.hexagram.judgmentEn}&rdquo;</p>
      <p className="text-xs text-stone-600">{p.footballInterpretation}</p>
    </div>
  );
}

export default function WorldCupPage({ params }: Props) {
  const u = UI[params.locale] || UI.en;
  const locale = params.locale;
  const today = new Date().toISOString().slice(0, 10);

  const todayMatches = getMatchesByDate(today).filter(m => m.home !== "TBD");
  const todayPredictions = todayMatches.map(predictMatch);

  const upcoming = MATCHES.filter(m => m.date >= today && m.home !== "TBD").slice(0, 12);

  const allMatches = MATCHES.filter(m => m.home !== "TBD");
  const matchesByDate = new Map<string, WCMatch[]>();
  for (const m of allMatches) {
    const existing = matchesByDate.get(m.date) || [];
    existing.push(m);
    matchesByDate.set(m.date, existing);
  }
  const dateEntries = Array.from(matchesByDate.entries()).sort(([a], [b]) => a.localeCompare(b));

  return (
    <div className="max-w-4xl mx-auto">
      {/* Warning Banner */}
      <div className="bg-amber-50 border border-amber-300 rounded-xl p-3 sm:p-4 mb-6 text-center">
        <p className="text-sm font-bold text-amber-800 mb-1">{u.warningBanner}</p>
        <p className="text-xs text-amber-700">{u.warningDetail}</p>
      </div>

      <div className="text-center mb-8">
        <h1 className="text-2xl sm:text-4xl font-bold mb-3" style={{ color: "var(--accent)" }}>{u.hero}</h1>
        <p className="text-sm sm:text-base text-stone-500 max-w-2xl mx-auto">{u.subtitle}</p>
        <p className="text-xs text-stone-400 mt-4 max-w-xl mx-auto">{u.intro}</p>
      </div>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-stone-700 mb-4">{u.todayLabel} — {today}</h2>
        {todayPredictions.length > 0 ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {todayPredictions.map((p) => <PredictionCard key={p.match.id} p={p} locale={locale} />)}
          </div>
        ) : (
          <div className="card-classic p-6 text-center text-sm text-stone-400">{u.noMatches}</div>
        )}
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-stone-700 mb-4">{u.groupsLabel}</h2>
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3">
          {GROUPS.map((g) => (
            <div key={g.name} className="card-classic p-3">
              <div className="text-sm font-semibold text-stone-700 mb-2">{u.groupLabel} {g.name}</div>
              {g.teams.map((t) => <div key={t} className="text-xs text-stone-600">{t}</div>)}
            </div>
          ))}
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-stone-700 mb-4">{u.upcomingLabel}</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {upcoming.map((m) => <PredictionCard key={m.id} p={predictMatch(m)} locale={locale} />)}
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-stone-700 mb-4">{u.fullScheduleLabel}</h2>
        {dateEntries.map(([date, matches]) => (
          <div key={date} className="mb-6">
            <h3 className="text-sm font-medium text-stone-500 mb-3 sticky top-14 bg-stone-50 py-1">{date}</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {matches.map((m) => <PredictionCard key={m.id} p={predictMatch(m)} locale={locale} />)}
            </div>
          </div>
        ))}
      </section>

      <section className="card-classic p-5 text-center mb-8">
        <h2 className="text-lg font-semibold text-stone-700 mb-2">{u.cta}</h2>
        <p className="text-sm text-stone-500 mb-4">{u.ctaText}</p>
        <Link href="/divination" className="inline-block px-6 py-3 rounded-xl text-sm font-medium btn-primary">
          {u.cta} &rarr;
        </Link>
      </section>

      <p className="text-center text-xs text-stone-400 mb-8">{u.disclaimer}</p>
    </div>
  );
}
