import type { Metadata } from "next";
import { Link } from "@/navigation";
import { MATCHES, GROUPS, type WCMatch, getMatchesByDate } from "@/data/world-cup-2026";
import { predictMatch, getAccuracyStats, type MatchPrediction, type Prediction } from "@/lib/world-cup";
import { BASE_URL } from "@/lib/config";
import WorldCupCTA from "@/components/WorldCupCTA";
import GuideCTA from "@/components/GuideCTA";
import EmailCaptureForm from "@/components/EmailCaptureForm";

type Props = { params: { locale: string } };

const UI: Record<string, {
  title: string; desc: string; ogTitle: string; ogDesc: string;
  hero: string; subtitle: string; intro: string;
  todayLabel: string; upcomingLabel: string; fullScheduleLabel: string;
  noMatches: string; groupLabel: string; vs: string;
  cta: string; ctaText: string; disclaimer: string; groupsLabel: string;
  warningBanner: string; warningDetail: string;
  homeWins: string; awayWins: string; drawLabel: string; accuracyTitle: string;
  correctBadge: string; wrongBadge: string; pendingLabel: string;
}> = {
  en: {
    title: "I Ching Predicts World Cup 2026 Final: Argentina vs Spain — Who Will Win? | Chinese Culture Studio",
    desc: "I Ching hexagram prediction for the 2026 FIFA World Cup Final: Argentina vs Spain (July 19, New York). Full knockout bracket, 64 predictions, track the oracle's accuracy.",
    ogTitle: "I Ching Predicts World Cup 2026 Final: Argentina vs Spain",
    ogDesc: "The ancient Chinese oracle predicts Argentina vs Spain in the World Cup Final. Full bracket, all knockout predictions & accuracy tracker.",
    hero: "I Ching x World Cup 2026: Argentina vs Spain Final", subtitle: "The 3,000-year-old Book of Changes predicts every World Cup match. Who will lift the trophy?",
    intro: "Each match gets one hexagram, deterministically generated from match date and teams. The hexagram's nature determines the predicted winner — home, away, or draw. Track the oracle's accuracy below.",
    todayLabel: "Today's Predictions", upcomingLabel: "Upcoming Matches", fullScheduleLabel: "Full Schedule",
    noMatches: "No matches scheduled for this date.", groupLabel: "Group", vs: "vs",
    cta: "Try I Ching Divination", ctaText: "Ask the I Ching your own question — about football or anything else.",
    disclaimer: "Disclaimer: This page is for entertainment purposes only. The I Ching (Book of Changes) is a 3,000-year-old Chinese philosophical and wisdom tradition, not a predictive tool. All hexagram predictions on this page are deterministically generated by a mathematical hash of match metadata (date + team names) and have no relationship to actual match outcomes. Do NOT use this content for gambling, betting, or any financial decisions. Chinese Culture Studio accepts no liability for any losses incurred through reliance on this entertainment content.",
    warningBanner: "FOR ENTERTAINMENT ONLY — NOT BETTING ADVICE",
    warningDetail: "These predictions are algorithmically generated from match metadata. Do not use for gambling or betting decisions.",
    groupsLabel: "Groups",
    homeWins: "Home Wins", awayWins: "Away Wins", drawLabel: "Draw", accuracyTitle: "Oracle Accuracy",
    correctBadge: "Correct", wrongBadge: "Wrong", pendingLabel: "Pending",
  },
  ru: {
    title: "И-Цзин предсказывает ЧМ-2026 — Кто победит? | Chinese Culture Studio",
    desc: "Гексаграммы И-Цзин для каждого матча ЧМ-2026. Кого древний оракул считает победителем? Отслеживайте точность прогнозов.",
    ogTitle: "И-Цзин предсказывает ЧМ-2026 — Кто победит?", ogDesc: "Древний оракул предсказывает каждый матч ЧМ. Отслеживайте точность.",
    hero: "И-Цзин x ЧМ-2026", subtitle: "3000-летняя Книга Перемен предсказывает каждый матч. Кто победит?",
    intro: "Каждый матч получает одну гексаграмму. Природа гексаграммы определяет прогноз — победа хозяев, гостей или ничья.",
    todayLabel: "Прогнозы на Сегодня", upcomingLabel: "Предстоящие Матчи", fullScheduleLabel: "Полное Расписание",
    noMatches: "На эту дату матчей нет.", groupLabel: "Группа", vs: "vs",
    cta: "Гадание И-Цзин", ctaText: "Задайте И-Цзин свой вопрос.",
    disclaimer: "Отказ от ответственности: эта страница предназначена исключительно для развлечения. И-Цзин (Книга Перемен) — это 3000-летняя китайская философская традиция мудрости, а не инструмент прогнозирования. НЕ используйте для ставок или азартных игр.",
    warningBanner: "ТОЛЬКО ДЛЯ РАЗВЛЕЧЕНИЯ — НЕ СОВЕТЫ ДЛЯ СТАВОК",
    warningDetail: "Эти прогнозы генерируются алгоритмически. Не используйте для азартных игр или ставок.",
    groupsLabel: "Группы",
    homeWins: "Победа Хозяев", awayWins: "Победа Гостей", drawLabel: "Ничья", accuracyTitle: "Точность Оракула",
    correctBadge: "Верно", wrongBadge: "Неверно", pendingLabel: "Ожидается",
  },
  ja: {
    title: "易経が占う2026年W杯 — 勝つのはどっち？ | Chinese Culture Studio",
    desc: "2026年FIFAワールドカップ全試合を易経八卦で勝敗予想。古代のオラクルはどちらが勝つと告げるか？予測精度を追跡。",
    ogTitle: "易経が占う2026年W杯 — 勝つのはどっち？", ogDesc: "古代中国のオラクルが全試合の勝敗を予想。精度を追跡せよ。",
    hero: "易経 x 2026 W杯", subtitle: "3000年の易経が全試合を予想。勝つのはどっち？",
    intro: "各試合に一卦。卦の性質が勝敗予想を決める — ホーム勝ち、アウェイ勝ち、引き分け。",
    todayLabel: "本日の予想", upcomingLabel: "今後の試合", fullScheduleLabel: "全スケジュール",
    noMatches: "この日に試合はありません。", groupLabel: "グループ", vs: "vs",
    cta: "易経占い", ctaText: "易経に質問してみてください。",
    disclaimer: "免責事項：このページは娯楽目的のみで提供されています。ギャンブルや賭博に使用しないでください。",
    warningBanner: "娯楽目的のみ — 賭博アドバイスではありません",
    warningDetail: "アルゴリズムで生成された娯楽コンテンツです。賭博に使用しないでください。",
    groupsLabel: "グループ",
    homeWins: "ホーム勝ち", awayWins: "アウェイ勝ち", drawLabel: "引き分け", accuracyTitle: "オラクル精度",
    correctBadge: "的中", wrongBadge: "外れ", pendingLabel: "未定",
  },
  ko: {
    title: "주역이 점치는 2026 월드컵 — 누가 이길까? | Chinese Culture Studio",
    desc: "2026 FIFA 월드컵 전 경기 주역 괘 승패 예측. 고대 오라클은 누가 이긴다고 말하는가? 예측 정확도를 추적하세요.",
    ogTitle: "주역이 점치는 2026 월드컵 — 누가 이길까?", ogDesc: "고대 중국 오라클이 모든 월드컵 경기를 예측합니다. 정확도를 확인하세요.",
    hero: "주역 x 2026 월드컵", subtitle: "3,000년 된 역경이 모든 경기를 예측합니다. 누가 이길까?",
    intro: "각 경기마다 하나의 괘. 괘의 성질이 승리 팀을 결정합니다 — 홈 승리, 원정 승리, 무승부.",
    todayLabel: "오늘의 예측", upcomingLabel: "예정된 경기", fullScheduleLabel: "전체 일정",
    noMatches: "경기가 없습니다.", groupLabel: "그룹", vs: "vs",
    cta: "주역 점술", ctaText: "주역에게 질문해보세요.",
    disclaimer: "면책 조항: 이 페이지는 오락 목적으로만 제공됩니다. 도박이나 베팅에 사용하지 마십시오.",
    warningBanner: "오락 목적으로만 제공 — 도박 조언이 아님",
    warningDetail: "알고리즘으로 생성된 오락 콘텐츠입니다. 도박에 사용하지 마십시오.",
    groupsLabel: "조",
    homeWins: "홈 승리", awayWins: "원정 승리", drawLabel: "무승부", accuracyTitle: "오라클 정확도",
    correctBadge: "적중", wrongBadge: "실패", pendingLabel: "대기",
  },
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const u = UI[params.locale] || UI.en;
  return {
    title: u.title, description: u.desc,
    openGraph: { title: u.ogTitle, description: u.ogDesc },
    robots: "index, follow",
    alternates: {
      languages: {
        en: `${BASE_URL}/world-cup`,
        ru: `${BASE_URL}/ru/world-cup`,
        ja: `${BASE_URL}/ja/world-cup`,
        ko: `${BASE_URL}/ko/world-cup`,
      },
    },
  };
}

const PREDICTION_LABELS: Record<string, Record<Prediction, string>> = {
  en: { home: "Home Wins", away: "Away Wins", draw: "Draw" },
  ru: { home: "Хозяева", away: "Гости", draw: "Ничья" },
  ja: { home: "ホーム勝ち", away: "アウェイ勝ち", draw: "引き分け" },
  ko: { home: "홈 승리", away: "원정 승리", draw: "무승부" },
};

function PredictionCard({ p, u, locale }: { p: MatchPrediction; u: typeof UI.en; locale: string }) {
  const labels = PREDICTION_LABELS[locale] || PREDICTION_LABELS.en;
  const predictionColor = p.prediction === "home" ? "var(--accent)" : p.prediction === "away" ? "#2563EB" : "#78716C";
  const hasResult = !!p.match.result;

  return (
    <div className="card-classic p-4">
      <div className="flex items-center justify-between mb-2">
        <div className="text-sm font-semibold text-stone-700">
          {p.match.home} <span className="text-stone-400 text-xs">vs</span> {p.match.away}
        </div>
        {hasResult ? (
          <span className="text-xs font-bold text-stone-600">
            {p.match.result!.home} - {p.match.result!.away}
          </span>
        ) : (
          <span className="text-xs text-stone-400">{u.pendingLabel}</span>
        )}
      </div>

      <div className="flex items-center gap-3 mb-2">
        <div className="w-9 h-9 rounded-full flex items-center justify-center text-sm font-bold text-white" style={{ backgroundColor: "var(--accent)" }}>
          {p.hexagram.id}
        </div>
        <div>
          <div className="text-sm font-medium" style={{ color: "var(--accent)" }}>{p.hexagram.nameEn}</div>
          <div className="text-xs text-stone-400">{p.hexagram.nameZh} - {p.hexagram.pinyin}</div>
        </div>
      </div>

      {/* Winner prediction */}
      <div className="flex items-center gap-2 mb-2">
        <span className="text-xs font-semibold px-2 py-0.5 rounded-full text-white"
          style={{ backgroundColor: predictionColor }}>
          {labels[p.prediction]}
        </span>
        {hasResult && (
          <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${p.correct ? "bg-green-100 text-green-700" : "bg-red-100 text-red-700"}`}>
            {p.correct ? u.correctBadge : u.wrongBadge}
          </span>
        )}
      </div>

      <p className="text-xs text-stone-500 italic mb-1">&ldquo;{p.hexagram.judgmentEn}&rdquo;</p>
      <p className="text-xs text-stone-600">{p.footballInterpretation}</p>
    </div>
  );
}

export default function WorldCupPage({ params }: Props) {
  const u = UI[params.locale] || UI.en;
  const locale = params.locale;
  const today = new Date().toISOString().slice(0, 10);
  const stats = getAccuracyStats();

  const todayMatches = getMatchesByDate(today).filter(m => m.home !== "TBD");
  const todayPredictions = todayMatches.map(predictMatch);

  const upcoming = MATCHES.filter(m => m.date >= today && m.home !== "TBD").slice(0, 12);

  const allMatches = MATCHES.filter(m => m.home !== "TBD");
  const matchesByDate = new Map<string, WCMatch[]>();
  for (const m of allMatches) {
    const existing = matchesByDate.get(m.date) || [];
    existing.push(m);
    matchesByDate.set(m.date, existing);
  }
  const dateEntries = Array.from(matchesByDate.entries()).sort(([a], [b]) => a.localeCompare(b));

  return (
    <div className="max-w-4xl mx-auto">
      {/* Warning Banner */}
      <div className="bg-amber-50 border border-amber-300 rounded-xl p-3 sm:p-4 mb-6 text-center">
        <p className="text-sm font-bold text-amber-800 mb-1">{u.warningBanner}</p>
        <p className="text-xs text-amber-700">{u.warningDetail}</p>
      </div>

      {/* Accuracy Stats */}
      {stats.total > 0 && (
        <div className="card-classic p-4 sm:p-5 mb-6">
          <h2 className="text-sm font-semibold text-stone-700 mb-3 text-center">{u.accuracyTitle}</h2>
          <div className="flex items-center justify-center gap-4 sm:gap-8 mb-3">
            <div className="text-center">
              <p className="text-2xl sm:text-3xl font-bold" style={{ color: stats.percentage >= 50 ? "var(--jade)" : "var(--accent)" }}>{stats.percentage}%</p>
              <p className="text-xs text-stone-400">{stats.correct}/{stats.total}</p>
            </div>
            <div className="flex gap-3 text-xs">
              <div className="text-center">
                <p className="font-semibold" style={{ color: "var(--accent)" }}>{stats.byPrediction.home.correct}/{stats.byPrediction.home.total}</p>
                <p className="text-stone-400">{u.homeWins}</p>
              </div>
              <div className="text-center">
                <p className="font-semibold text-blue-600">{stats.byPrediction.away.correct}/{stats.byPrediction.away.total}</p>
                <p className="text-stone-400">{u.awayWins}</p>
              </div>
              <div className="text-center">
                <p className="font-semibold text-stone-500">{stats.byPrediction.draw.correct}/{stats.byPrediction.draw.total}</p>
                <p className="text-stone-400">{u.drawLabel}</p>
              </div>
            </div>
          </div>
        </div>
      )}

      <WorldCupCTA />

      <div className="text-center mb-8">
        <h1 className="text-2xl sm:text-4xl font-bold mb-3" style={{ color: "var(--accent)" }}>{u.hero}</h1>
        <p className="text-sm sm:text-base text-stone-500 max-w-2xl mx-auto">{u.subtitle}</p>
        <p className="text-xs text-stone-400 mt-4 max-w-xl mx-auto">{u.intro}</p>
      </div>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-stone-700 mb-4">{u.todayLabel} — {today}</h2>
        {todayPredictions.length > 0 ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {todayPredictions.map((p) => <PredictionCard key={p.match.id} p={p} u={u} locale={locale} />)}
          </div>
        ) : (
          <div className="card-classic p-6 text-center text-sm text-stone-400">{u.noMatches}</div>
        )}
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-stone-700 mb-4">{u.groupsLabel}</h2>
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3">
          {GROUPS.map((g) => (
            <div key={g.name} className="card-classic p-3">
              <div className="text-sm font-semibold text-stone-700 mb-2">{u.groupLabel} {g.name}</div>
              {g.teams.map((t) => <div key={t} className="text-xs text-stone-600">{t}</div>)}
            </div>
          ))}
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-stone-700 mb-4">{u.upcomingLabel}</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {upcoming.map((m) => <PredictionCard key={m.id} p={predictMatch(m)} u={u} locale={locale} />)}
        </div>
      </section>

      <section className="mb-8">
        <h2 className="text-lg font-semibold text-stone-700 mb-4">{u.fullScheduleLabel}</h2>
        {dateEntries.map(([date, matches]) => (
          <div key={date} className="mb-6">
            <h3 className="text-sm font-medium text-stone-500 mb-3 sticky top-14 bg-stone-50 py-1">{date}</h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {matches.map((m) => <PredictionCard key={m.id} p={predictMatch(m)} u={u} locale={locale} />)}
            </div>
          </div>
        ))}
      </section>

      <section className="card-classic p-5 text-center mb-8">
        <h2 className="text-lg font-semibold text-stone-700 mb-2">{u.cta}</h2>
        <p className="text-sm text-stone-500 mb-4">{u.ctaText}</p>
        <Link href="/divination" className="inline-block px-6 py-3 rounded-xl text-sm font-medium btn-primary">
          {u.cta} &rarr;
        </Link>
      </section>

      <div className="max-w-md mx-auto mb-8">
        <EmailCaptureForm source="divination" />
      </div>

      <p className="text-center text-xs text-stone-400 mb-8">{u.disclaimer}</p>

      <GuideCTA href="/divination" service="divination" variant="sticky" />
    </div>
  );
}
